# docker-compose.yml
version: "3.8"

services:
  app:
    build: .
    volumes:
      # - type: bind
      #   source: .
      #   target: /app
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
      - sqlite

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: callcenter_cleaned_data
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  sqlite:
    image: nouchka/sqlite3
    volumes:
      - sqlite-db:/sqlite.db
      # - type: bind
      #   source: ./sqlite.db
      #   target: /sqlite.db

volumes:
  db-data:
  sqlite-db:
