# docker-compose.yml
version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: call_center_data
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33060:33060"
    volumes:
      - db-data:/var/lib/mysql
      - ./backup:/backup

volumes:
  node_modules:
  db-data:
